name: ContainerProtect
main: no.atc.floyd.bukkit.cp.ContainerProtect
version: 1.21
website: http://minecraft.atc.no/plugins
author: FloydATC
depend: [BanPlugin]
description: >
             Chest, furnace and dispenser protection
commands:
  cp:
    description: Set protection mode 1=public, 2=private, 3=player, 4=group
    usage: /<command> [1/PUblic|2/PRivate|3/PLayer <name>|4/Group <group>]
