name: "${project.name}"
main: no.atc.floyd.bukkit.cp.ContainerProtect
version: "${project.version}"
website: "${project.url}"
author: FloydATC
depend: [BanPlugin]
description: "${project.description}"

commands:
  cp:
    description: Set protection mode 1=public, 2=private, 3=player, 4=group
    usage: /<command> [1/PUblic|2/PRivate|3/PLayer <name>|4/Group <group>]
